# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Check Online Document Building
permissions: {}

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Prepare files (ignore error)
      continue-on-error: true
      shell: bash
      run: |
        mkdir opea
        # mkdir opea/docs
        # echo "mv docs' file/folder to opea/doc"
        # ls -la
        # echo "2"
        # mv ./* opea/docs
        # ls -la
        # echo "3"
        # ls -la opea/docs

    - name: Build Online Document
      shell: bash
      run: |
        git config --local --get remote.origin.url
        echo "build online doc"
        bash scripts/build.sh
