# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Check Online Document Building
permissions: {}

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build Online Document

      run: |
        git config --local --get remote.origin.url
        mkdir opea
        mkdir opea/docs
        echo "mv docs' file/folder to opea/doc"
        mv * opea/docs
        cd opea/docs
        echo "build online doc"
        bash scripts/build.sh f